# TMUX config

# Mouse
set -g mouse on

# clipboard
set -s set-clipboard on

# vi keys + bindings
setw -g mode-keys vi
bind [ copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi r send -X rectangle-toggle
bind p paste-buffer

# local machine: Y -> system clipboard
if-shell '[ -z "$SSH_CONNECTION" ] && [ "$(uname)" = "Darwin" ]' \
  'bind -T copy-mode-vi Y send -X copy-pipe-and-cancel "pbcopy"'

if-shell '[ -z "$SSH_CONNECTION" ] && [ "$(uname)" = "Linux" ]' \
  'bind -T copy-mode-vi Y send -X copy-pipe-and-cancel "xclip -selection clipboard"'

# remote over SSH: Y -> OSC 52 directly to client clipboard
if-shell '[ -n "$SSH_CONNECTION" ]' {
  bind -T copy-mode-vi Y send -X copy-pipe-and-cancel 'b64=$(base64 | tr -d "\n"); printf "\033]52;c;%s\007" "$b64" > #{client_tty}'
}

